### PR TITLE
BUG-6: Event Picture is Uploaded before Review

### LINKED ISSUE #104: BUG-6: Event Picture is Uploaded before Review
**Describe The Bug**

When creating an event, the event photo is uploaded before being able to review the event.

**To Reproduce**

1. Start the application using ```nx serve mull-ui``` & ```nx serve mull-api```
2. Go to the create event page.
1. Have your browser developer tools open on the network tab.
1. Fill out the form and press the "Submit" button.
1. See that the picture is uploaded before reviewing.

**Expected Behavior**

Event Photo should be uploaded after reviewing the form.

**Screenshots**
Before Event Review:
image

At Event Review:
image

**Bug Strategy**
- [ ] Fix it now
- [x] Fix it later

### PR DESCRIPTION
**Pull request by bit172**
This PR closes #104.

### CODE REVIEW

**Review by osahtout — CHANGES_REQUESTED** [review]
Screen Shot 2020-12-30 at 5 48 05 PM

The changes made do prevent the images from being uploaded when clicking done but, when clicking create the page stays in the review  (doesn't redirect to my events) and I was able to create the same event and upload the same image multiple times. 

I tested this on Linux and MacOS

File: apps/mull-ui/src/app/pages/create-event/create-event.tsx [hunk 1]
```diff
@@ -118,32 +118,24 @@ const CreateEventPage = ({ history }: CreateEventProps) => {
...
+        } = await uploadFile({ variables: { file: file } });
+        await createEvent({
+          variables: {
+            createEventInput: {
+              ...payload,
+              image: { id: uploadedFile.id, mediaType: uploadedFile.mediaType },
+            },
+          },
+        });
+        updateToast(toast.TYPE.SUCCESS, 'Event Created');
```
Comment (cristian-aldea) [inline apps/mull-ui/src/app/pages/create-event/create-event.tsx:134]: Like Omar mentioned, the user isn't redirected to home after creating the event since the `history.push` call was removed from `createMullEvent`, but not added back to `onSubmit`

```suggestion
        updateToast(toast.TYPE.SUCCESS, 'Event Created');
        history.push(ROUTES.HOME);
```

File: apps/mull-ui/src/app/pages/create-event/create-event.tsx [hunk 2]
```diff
@@ -118,32 +118,24 @@ const CreateEventPage = ({ history }: CreateEventProps) => {
     }),
 
     onSubmit: async (values) => {
```
Comment (cristian-aldea) [inline apps/mull-ui/src/app/pages/create-event/create-event.tsx]: values isn't being used. I think we can remove it.

**Review by cristian-aldea — CHANGES_REQUESTED** [review]
Everything looks great! Noticed the same problem as omar, but its an easy fix

**Review by cristian-aldea — DISMISSED** [review]

**Review by osahtout — DISMISSED** [review]

**Review by cristian-aldea — APPROVED** [review]

**Review by osahtout — APPROVED** [review]
